---
version: "3"

services:
  mysql:
    image: mysql

    network_mode: "host"

    environment:
      MYSQL_ROOT_PASSWORD: hackandpay
      MYSQL_DATABASE: hackandpay
      MYSQL_USER: hackandpay
      MYSQL_PASSWORD: hackandpay