[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/badoux/checkmail"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.x.x"

[[constraint]]
  name = "github.com/dimfeld/httptreemux"
  version = "5.x.x"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.x.x"

[[constraint]]
  branch = "v2"
  name = "github.com/go-validator/validator"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.x.x"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.x.x"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/rubenv/sql-migrate"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.x.x"

[[constraint]]
  name = "github.com/vattle/sqlboiler"
  version = "2.x.x"

[[constraint]]
  name = "github.com/x-cray/logrus-prefixed-formatter"
  version = "0.5.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/ldap.v2"
  version = "2.x.x"

[[constraint]]
  name = "gopkg.in/nullbio/null.v6"
  version = "6.3.0"

[[constraint]]
  name = "github.com/ericlagergren/decimal"
  version = "3.x.x"
